<?php 
/*------------------------------------------------------------------------
# Venustheme_Gallery Module, Build for Magento
# ------------------------------------------------------------------------
# @Copyright (C) 2008-2012 Venustheme. All Rights Reserved.
# @License - Copyrighted Commercial Software
# @Author: Venustheme
# @Websites: http://venustheme.com
-------------------------------------------------------------------------*/ 	
?>
<?php
	$config = $this->_config;
	$moduleId = rand().time();
	$enabled = (!isset($config['show'])) ? '1' : $config['show'];
	
	$title = $this->getConfig('title', '');
	
	$theme = $this->getConfig('theme', 'default');
	
	$tmp = $this->getConfig('moduleWidth', 'auto');
	$moduleWidth = ($tmp == 'auto') ? 'auto' : (int)$tmp;
	$tmp = $this->getConfig('moduleHeight', 'auto');
	$moduleHeight = ($tmp == 'auto') ? 'auto' : (int)$tmp;
	
	$show_title = (!isset($config['show_title'])) ? '0' : $config['show_title']; // title product
	$show_date = (!isset($config['show_date'])) ? '0' : $config['show_date'];
	$show_price = (!isset($config['show_price'])) ? '1' : $config['show_price'];
	$priceSpecial = (!isset($config['show_pricewithout'])) ? '1' : $config['show_pricewithout'];
	$show_desc = (!isset($config['show_desc'])) ? '1' : $config['show_desc'];
	$show_addcart = (!isset($config['show_addcart'])) ? '1' : $config['show_addcart'];
	
	$show_button = (!isset($config['show_button'])) ? '1' : $config['show_button'];
	$show_pager = (!isset($config['show_pager'])) ? '1' : $config['show_pager'];
	
	$auto_play = (!isset($config['auto_play'])) ? '1' : $config['auto_play'];
	$auto_play = ($auto_play == 1) ? 'true' : 'false';
	
	
	$tp = $this->getConfig('slide_width', 'auto');
	$slide_width = ($tp == 'auto') ? '\'auto\'' : (int)$tp;
	$tp = $this->getConfig('slide_height', 'auto');
	$slide_height = ($tp == 'auto') ? '\'auto\'' : (int)$tp;
	
	$scroll_items = $this->getConfig('scroll_items', '1');
	$limit_cols = $this->getConfig('limit_cols', '4');
	$duration = $this->getConfig('duration', 501);
	
?>
<?php if($enabled == 1)://start enabled?>
<div class="ves-gallery <?php echo $theme;?>" style="width:<?php echo $moduleWidth;?>;height:<?php echo $moduleHeight;?>">
	<section class="gallery-widget"><!--start tag section-->
		<header>
			<h3 class="gallery-title"><?php echo $title;?></h3>
		</header>
		<div class="list-gallery responsive"><!--start class="list-gallery"-->
			<ul id="ves-gallery-<?php echo $moduleId;?>" class="gallery-news clearfix"><!--start tag ul-->
				<?php foreach($items as $item): //start foreach?>
				<li><!--start tag li-->
					<article>
						<div class="gallery-item box-hover clearfix">
							<div class="image-thumb">
								<img class="responsive-img" src="<?php echo $item['mainImage'];?>" alt="<?php echo $item['title'];?>"/>
							</div>
							<div class="entry-content">
								<?php if($show_date)://start show_date?>
									<div class="entry-date"><?php echo $item['dateAdd'];?></div>
								<?php endif; //end show_date?>
								
								<?php if($show_price)://start show_price?>
									<div class="entry-price"><?php echo $item['price'];?></div>
								<?php endif; //end show_price?>
								
								<?php if($priceSpecial)://start show_priceSpecial?>
									<div class="entry-price-discount"><?php echo $item['price_ves_reduction'];?></div>
								<?php endif; //end show_priceSpecial?>
								
								<?php if($show_title)://start show_title?>
									<h4 class="entry-title">
										<a href="<?php echo $item['link'];?>"><?php echo $item['title'];?></a>
									</h4>
								<?php endif; //end show_title?>
								
								<?php if($show_desc)://start show_desc?>
									<p><?php echo $item['des'];?></p>
								<?php endif; //end show_desc?>
								
								<a href="<?php echo $item['link'];?>"><?php echo $this->__('Detail');?></a>
								
							</div>
						</div>
					</article>				
				</li><!--end tag li-->
				<?php endforeach; //end foreach?>
			</ul><!--end tag ul-->
			<?php if($show_button): //start show_button?>
			<div class="gallery-nav">
				<a id="vesprev-<?php echo $moduleId;?>" class="prev" href="#">&nbsp;</a>
				<a id="vesnext-<?php echo $moduleId;?>" class="next" href="#">&nbsp;</a>
			</div>
			<?php endif; //end show_button?>
			<?php if($show_pager): //start show_pager?>
			<div id="vespager-<?php echo $moduleId;?>" class="ves-pager"></div>
			<?php endif; //end show_pager?>
		</div><!--end class="list-gallery"-->
	</section><!--end tag section-->
</div>
<script type="text/javascript">
	jQuery('#ves-gallery-<?php echo $moduleId;?>').carouFredSel({
		responsive:true,
		prev: '#vesprev-<?php echo $moduleId;?>',
		next: '#vesnext-<?php echo $moduleId;?>',
		pagination: "#vespager-<?php echo $moduleId;?>",
		auto: {
			play:<?php echo $auto_play;?>,
			duration:550
		},
		width: <?php echo $slide_width;?>,
		height: <?php echo $slide_height;?>,
		scroll: {
			items : <?php echo $scroll_items;?>,
			duration : <?php echo $duration;?>,
		},
		items:{
			width:200,
			visible:{
				min:1,
				max:<?php echo $limit_cols;?>
			}
		}
	});	
</script>
<?php endif;//end enabled menu?>
<div style="clear:both;"></div>
